name: Publish docker image
on: [push]
jobs:
publish-itsxpress-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the itsxpress Docker image
run: |
       docker build . --tag ghcr.io/usda-ars-gbru/itsxpress/itsxpress:latest
       docker run ghcr.io/usda-ars-gbru/itsxpress/itsxpress:latest
       docker push ghcr.io/usda-ars-gbru/itsxpress/itsxpress:latest