name: GitHub Action Apple Silicon Test

#A workflow (github action) that tests installation of itsxpress on Apple Silicon (arm64) using conda
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14
    steps:     
    - name: Install conda
      run: |
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        CONDA_SUBDIR=osx-64 conda create -n itsxpressenv -c bioconda -c conda-forge itsxpress
        conda init
        source activate itsxpressenv
        conda  config --env --set subdir osx-64
    - name: Install Dependencies
      run: |
        source activate itsxpressenv
        conda  config --env --set subdir osx-64
        conda install biopython
        pip install pyzstd
        pip install pytest
        pip install .
        #qiime
        #itsxpress
        #qiime itsxpress
        #ls

    - name: Test with pytest
      run: |
        source activate testenv
        pytest
