name: GitHub Action Apple Silicon Test

on:
  push:
    branches:
      - main
jobs:
  example-13:
    name: Ex13 (os=${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-14"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
      - run:   |
          #sudo apt update
          #sudo apt install gcc-10 g++-10
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
          echo $CONDA_PREFIX
          $CONDA/bin/conda list
          $CONDA/bin/conda info --base
          CONDA_SUBDIR=osx-64 conda create --name testenv python=3.8.16
          #CONDA_PREFIX=/usr/share/miniconda/envs/testenv
          $CONDA/bin/conda info
          $CONDA/bin/conda list
          
