name: GitHub Actions Weekly Build (V2)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */7 * *"
    
jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
    - run:   |
        sudo apt update
        sudo apt install gcc-10 g++-10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        echo $CONDA_PREFIX
        $CONDA/bin/conda list
        $CONDA/bin/conda info --base
        CONDA_PREFIX=/usr/share/miniconda
        echo $CONDA_PREFIX
        
#     - name: Initiate conda channels
#       uses: conda-incubator/setup-miniconda@v2
#       with:
#         channels: conda-forge,bioconda,default

#     - name: Set up environment
#       run: |
#         wget https://data.qiime2.org/distro/core/qiime2-2023.5-py38-linux-conda.yml
#         $CONDA/bin/conda env update --file qiime2-2023.5-py38-linux-conda.yml --name base
#     - name: Install Dependencies
#       run: |
#         $CONDA/bin/conda install biopython
#         pip install pyzstd
#         pip install pytest
#         pip install .
#         qiime
#         itsxpress
#         qiime itsxpress
#         ls

#     - name: Test with pytest
#       run: |
#         pytest
