name: Python Package using Conda

on:
  push:
    branches:
      - version2

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Set up environment
      run: |
        conda create --name testenv python
        source activate testenv
    - name: Install Dependencies
      run: |
        source activate testenv
        conda install -c bioconda vsearch=2.22.1
        vsearch --version
        conda install -c bioconda hmmer
        conda install biopython
        pip install pyzstd
        pip install pytest
        pip install -e .
    - name: Test with pytest
      run: |
        source activate testenv
        pytest
