name: GitHub Action Apple Silicon Test

#A workflow (github action) that tests installation of itsxpress on Apple Silicon (arm64) using conda
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-14
    steps:     
    - name: Install conda
      run: |
        curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
        bash Miniconda3-latest-MacOSX-x86_64.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        conda init bash
        conda create -n test-itsxpress python=${{ matrix.python-version }}
        conda activate test-itsxpress
        conda install -c conda-forge biopython hmmer vsearch pyzstd
