name: Python Package using Conda

on:
  push:
    branches:
      - version2

jobs:
  build-linux:
    runs-on: ubuntu-20.04    
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - run:   |
         sudo apt update
         sudo apt install gcc-10 g++-10
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Initiate conda channels
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: testenv
        python-version: 3.7
        channels: conda-forge,bioconda
        allow-softlinks: true
        channel-priority: flexible
        show-channel-urls: true
        use-only-tar-bz2: true
          
    - name: Set up environment
      run: |
        conda create --name testenv python=3.7
        source activate testenv
        conda search zlib
    - name: Install Dependencies
      run: |
        source activate testenv
        conda install -c bioconda vsearch=2.22.1
        vsearch --version
        #conda install -c bioconda hmmer
        #conda install biopython
        #pip install pyzstd
        #pip install pytest
        #pip install -e .
    - name: Test with pytest
      run: |
        source activate testenv
        #pytest
